### ISSUE TITLE
Version 1.1.2+ roadmap

### ISSUE THREAD

**Issue by evs-dev** [evs-dev/SignBartering#3]
**Features for SignBartering v1.2.0 (or maybe beyond):**
- [x] Add "infinitesell" ([isell]) for operators only, allowing unobtainable or rare items to be infinitely purchased
- [x] (0fc6537a69b0fa8b0d24f20bbaec075f70a48ab0) Double chest support
- [x] (0fc6537a69b0fa8b0d24f20bbaec075f70a48ab0) All containers support
- [x] (63930d42379688520ca5212283a8b82fd4f3fcc1) More messages ("your shop is out of stock")

**Other things that need to be done:**
- [x] (#4) Remove zombie code
- [x] (#4) Change enchanted book code to work for any similar item (like player_head)
- [x] (7ad3bed84445ee26cf24056ad0b2292331f47dfa) Have container check all surrounding blocks for sign rather than only its front
